[package]
name = "nest_struct"
version = "0.1.2"
edition = "2021"
description = "Nest struct definitions with minimal syntax changes"
license = "MIT"

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1"
quote = "1"
syn = "2"

[dev-dependencies]
macrotest = "1"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

[lib]
proc-macro = true
