[package]
name = "nest_struct"
version = "0.1.0"
edition = "2021"
description = "Nest struct definitions with minimal syntax changes"
license = "MIT"

[dependencies]
quote = "1.0.37"

[dev-dependencies]
macrotest = "1"

[lib]
proc-macro = true
